package com.vaultbrain.core.common.model

/**
 * Canonical experience identifiers.
 *
 * Experiences are user intents layered on top of lenses. A single lens can host
 * many experiences (e.g. Money lens contains Expense, Subscription, Budget, etc.).
 */
object ExperienceId {
    // Money / Finance
    const val EXPENSE = "EXPENSE"
    const val INCOME = "INCOME"
    const val SUBSCRIPTION = "SUBSCRIPTION"
    const val BILL = "BILL"
    const val BUDGET_TRACKER = "BUDGET_TRACKER"
    const val INVOICE_FOR_WORK = "INVOICE_FOR_WORK"
    const val TAX_DOCUMENT = "TAX_DOCUMENT"
    const val INVESTMENT_RECORD = "INVESTMENT_RECORD"
    const val INSURANCE_PAYMENT = "INSURANCE_PAYMENT"
    const val BANK_STATEMENT = "BANK_STATEMENT"
    const val CREDIT_CARD_STATEMENT = "CREDIT_CARD_STATEMENT"
    const val LOAN_PAYMENT = "LOAN_PAYMENT"
    const val GROCERY_LIST = "GROCERY_LIST"
    const val GROCERY_RECEIPT = "GROCERY_RECEIPT"
    const val PET_EXPENSE = "PET_EXPENSE"
    const val TUITION_FEE = "TUITION_FEE"

    // Health
    const val PRESCRIPTION = "PRESCRIPTION"
    const val MEDICATION_SCHEDULE = "MEDICATION_SCHEDULE"
    const val LAB_RESULT = "LAB_RESULT"
    const val HEALTH_INSURANCE_CLAIM = "HEALTH_INSURANCE_CLAIM"
    const val HEALTH_INSURANCE_CARD = "HEALTH_INSURANCE_CARD"
    const val VACCINATION_RECORD = "VACCINATION_RECORD"
    const val DOCTOR_NOTE = "DOCTOR_NOTE"
    const val FITNESS_TRACKER = "FITNESS_TRACKER"
    const val DENTAL_VISIT = "DENTAL_VISIT"
    const val OPTICAL_PRESCRIPTION = "OPTICAL_PRESCRIPTION"
    const val ALLERGY_RECORD = "ALLERGY_RECORD"
    const val PHYSIOTHERAPY_PLAN = "PHYSIOTHERAPY_PLAN"
    const val MENTAL_HEALTH_NOTE = "MENTAL_HEALTH_NOTE"
    const val BLOOD_DONATION = "BLOOD_DONATION"

    // Travel
    const val FLIGHT_TICKET = "FLIGHT_TICKET"
    const val HOTEL_BOOKING = "HOTEL_BOOKING"
    const val BOARDING_PASS = "BOARDING_PASS"
    const val TRAVEL_EXPENSE = "TRAVEL_EXPENSE"
    const val VISA = "VISA"
    const val ITINERARY = "ITINERARY"
    const val CAR_RENTAL = "CAR_RENTAL"
    const val TRAIN_TICKET = "TRAIN_TICKET"
    const val BUS_TICKET = "BUS_TICKET"
    const val FERRY_TICKET = "FERRY_TICKET"
    const val TRAVEL_INSURANCE = "TRAVEL_INSURANCE"
    const val TRAVEL_CHECKLIST = "TRAVEL_CHECKLIST"
    const val AIRPORT_LOUNGE = "AIRPORT_LOUNGE"
    const val EVENT_TICKET = "EVENT_TICKET"

    // Bureaucracy / Identity
    const val PASSPORT = "PASSPORT"
    const val ID_CARD = "ID_CARD"
    const val DRIVERS_LICENSE = "DRIVERS_LICENSE"
    const val RESIDENCE_PERMIT = "RESIDENCE_PERMIT"
    const val BUSINESS_CARD = "BUSINESS_CARD"
    const val BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE"
    const val MARRIAGE_CERTIFICATE = "MARRIAGE_CERTIFICATE"
    const val NOTARIZED_DOCUMENT = "NOTARIZED_DOCUMENT"
    const val TAX_RESIDENCY_CERTIFICATE = "TAX_RESIDENCY_CERTIFICATE"
    const val PROFESSIONAL_LICENSE = "PROFESSIONAL_LICENSE"

    // Home
    const val WARRANTY = "WARRANTY"
    const val APPLIANCE_MANUAL = "APPLIANCE_MANUAL"
    const val HOME_INVENTORY = "HOME_INVENTORY"
    const val RENT_CONTRACT = "RENT_CONTRACT"
    const val UTILITY_BILL = "UTILITY_BILL"
    const val ELECTRICITY_BILL = "ELECTRICITY_BILL"
    const val WATER_BILL = "WATER_BILL"
    const val GAS_BILL = "GAS_BILL"
    const val INTERNET_BILL = "INTERNET_BILL"
    const val TELECOM_BILL = "TELECOM_BILL"
    const val PROPERTY_DEED = "PROPERTY_DEED"
    const val MORTGAGE_STATEMENT = "MORTGAGE_STATEMENT"
    const val HOME_INSURANCE_POLICY = "HOME_INSURANCE_POLICY"
    const val APPLIANCE_REGISTRATION = "APPLIANCE_REGISTRATION"
    const val UTILITY_SETUP = "UTILITY_SETUP"
    const val INSURANCE_POLICY = "INSURANCE_POLICY"

    // Car
    const val CAR_INSURANCE = "CAR_INSURANCE"
    const val CAR_SERVICE = "CAR_SERVICE"
    const val PARKING_TICKET = "PARKING_TICKET"
    const val FINE_TICKET = "FINE_TICKET"
    const val FUEL_RECEIPT = "FUEL_RECEIPT"
    const val CAR_REGISTRATION = "CAR_REGISTRATION"
    const val CAR_LOAN = "CAR_LOAN"
    const val TOLL_RECEIPT = "TOLL_RECEIPT"
    const val PARKING_PERMIT = "PARKING_PERMIT"
    const val CAR_INSPECTION = "CAR_INSPECTION"

    // Shopping
    const val PRICE_COMPARE = "PRICE_COMPARE"
    const val GIFT_IDEA = "GIFT_IDEA"
    const val COUPON = "COUPON"
    const val RETURN_POLICY = "RETURN_POLICY"
    const val ORDER_CONFIRMATION = "ORDER_CONFIRMATION"
    const val SHIPPING_TRACKING = "SHIPPING_TRACKING"
    const val LOYALTY_CARD = "LOYALTY_CARD"
    const val GIFT_RECEIPT = "GIFT_RECEIPT"
    const val WISHLIST = "WISHLIST"

    // Media
    const val WEB_ARTICLE = "WEB_ARTICLE"
    const val WATCHLIST = "WATCHLIST"
    const val ALREADY_WATCHED = "ALREADY_WATCHED"
    const val READING_LIST = "READING_LIST"
    const val ALREADY_READ = "ALREADY_READ"
    const val MUSIC_PLAYLIST = "MUSIC_PLAYLIST"
    const val GAME_WISHLIST = "GAME_WISHLIST"
    const val RECIPE = "RECIPE"
    const val PODCAST = "PODCAST"
    const val AUDIOBOOK = "AUDIOBOOK"
    const val EBOOK = "EBOOK"
    const val ONLINE_COURSE = "ONLINE_COURSE"
    const val CONCERT_TICKET = "CONCERT_TICKET"
    const val MUSEUM_TICKET = "MUSEUM_TICKET"
    const val THEATER_TICKET = "THEATER_TICKET"

    // Productivity
    const val NOTE = "NOTE"
    const val REMINDER = "REMINDER"
    const val MEETING_NOTES = "MEETING_NOTES"
    const val STUDY_MATERIAL = "STUDY_MATERIAL"
    const val BOOKMARK = "BOOKMARK"
    const val TODO_LIST = "TODO_LIST"
    const val HABIT_TRACKER = "HABIT_TRACKER"
    const val GOAL = "GOAL"
    const val PROJECT_PLAN = "PROJECT_PLAN"
    const val JOURNAL = "JOURNAL"
    const val GRATITUDE_LOG = "GRATITUDE_LOG"

    // Services
    const val SERVICE_CONTRACT = "SERVICE_CONTRACT"
    const val APPOINTMENT = "APPOINTMENT"
    const val QUOTE = "QUOTE"
    const val PHONE_PLAN = "PHONE_PLAN"
    const val INTERNET_PLAN = "INTERNET_PLAN"
    const val GYM_MEMBERSHIP = "GYM_MEMBERSHIP"
    const val STREAMING_SERVICE = "STREAMING_SERVICE"
    const val CLOUD_STORAGE = "CLOUD_STORAGE"
    const val CLEANING_SERVICE = "CLEANING_SERVICE"

    // Scam guard
    const val SUSPICIOUS_MESSAGE = "SUSPICIOUS_MESSAGE"
    const val PHISHING_REPORT = "PHISHING_REPORT"
    const val FRAUD_RECORD = "FRAUD_RECORD"
    const val FAKE_INVOICE = "FAKE_INVOICE"
    const val FAKE_CHECK = "FAKE_CHECK"
    const val ADVANCE_FEE_FRAUD = "ADVANCE_FEE_FRAUD"
    const val LOTTERY_SCAM = "LOTTERY_SCAM"
    const val TECH_SUPPORT_SCAM = "TECH_SUPPORT_SCAM"
    const val ROMANCE_SCAM = "ROMANCE_SCAM"

    /** Generic fallback when the user does not want to choose. */
    const val GENERIC = "GENERIC"

    val ALL_EXPERIENCES: Set<String> = setOf(
        // Money
        EXPENSE, INCOME, SUBSCRIPTION, BILL, BUDGET_TRACKER, INVOICE_FOR_WORK,
        TAX_DOCUMENT, INVESTMENT_RECORD, INSURANCE_PAYMENT, BANK_STATEMENT,
        CREDIT_CARD_STATEMENT, LOAN_PAYMENT, GROCERY_LIST, GROCERY_RECEIPT, PET_EXPENSE, TUITION_FEE,
        // Health
        PRESCRIPTION, MEDICATION_SCHEDULE, LAB_RESULT, HEALTH_INSURANCE_CLAIM,
        HEALTH_INSURANCE_CARD, VACCINATION_RECORD, DOCTOR_NOTE, FITNESS_TRACKER, DENTAL_VISIT,
        OPTICAL_PRESCRIPTION, ALLERGY_RECORD, PHYSIOTHERAPY_PLAN, MENTAL_HEALTH_NOTE,
        BLOOD_DONATION,
        // Travel
        FLIGHT_TICKET, HOTEL_BOOKING, BOARDING_PASS, TRAVEL_EXPENSE, VISA, ITINERARY, CAR_RENTAL,
        TRAIN_TICKET, BUS_TICKET, FERRY_TICKET, TRAVEL_INSURANCE, TRAVEL_CHECKLIST, AIRPORT_LOUNGE,
        EVENT_TICKET,
        // Bureaucracy
        PASSPORT, ID_CARD, DRIVERS_LICENSE, RESIDENCE_PERMIT, BUSINESS_CARD,
        BIRTH_CERTIFICATE, MARRIAGE_CERTIFICATE, NOTARIZED_DOCUMENT,
        TAX_RESIDENCY_CERTIFICATE, PROFESSIONAL_LICENSE,
        // Home
        WARRANTY, APPLIANCE_MANUAL, HOME_INVENTORY, RENT_CONTRACT, UTILITY_BILL,
        ELECTRICITY_BILL, WATER_BILL, GAS_BILL, INTERNET_BILL, TELECOM_BILL,
        PROPERTY_DEED, MORTGAGE_STATEMENT, HOME_INSURANCE_POLICY, APPLIANCE_REGISTRATION,
        UTILITY_SETUP, INSURANCE_POLICY,
        // Car
        CAR_INSURANCE, CAR_SERVICE, PARKING_TICKET, FINE_TICKET, FUEL_RECEIPT,
        CAR_REGISTRATION, CAR_LOAN, TOLL_RECEIPT, PARKING_PERMIT, CAR_INSPECTION,
        // Shopping
        PRICE_COMPARE, GIFT_IDEA, COUPON, RETURN_POLICY,
        ORDER_CONFIRMATION, SHIPPING_TRACKING, LOYALTY_CARD, GIFT_RECEIPT, WISHLIST,
        // Media
        WEB_ARTICLE, WATCHLIST, ALREADY_WATCHED, READING_LIST, ALREADY_READ, MUSIC_PLAYLIST, GAME_WISHLIST, RECIPE,
        PODCAST, AUDIOBOOK, EBOOK, ONLINE_COURSE, CONCERT_TICKET, MUSEUM_TICKET, THEATER_TICKET,
        // Productivity
        NOTE, REMINDER, MEETING_NOTES, STUDY_MATERIAL, BOOKMARK,
        TODO_LIST, HABIT_TRACKER, GOAL, PROJECT_PLAN, JOURNAL, GRATITUDE_LOG,
        // Services
        SERVICE_CONTRACT, APPOINTMENT, QUOTE,
        PHONE_PLAN, INTERNET_PLAN, GYM_MEMBERSHIP, STREAMING_SERVICE, CLOUD_STORAGE, CLEANING_SERVICE,
        // Scam guard
        SUSPICIOUS_MESSAGE, PHISHING_REPORT, FRAUD_RECORD,
        FAKE_INVOICE, FAKE_CHECK, ADVANCE_FEE_FRAUD, LOTTERY_SCAM, TECH_SUPPORT_SCAM, ROMANCE_SCAM,
        GENERIC
    )

    fun canonicalOrNull(value: String?): String? = value
        ?.trim()
        ?.uppercase()
        ?.takeIf { it in ALL_EXPERIENCES }
}
